apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  nfs:
    server: nfs-server.airflow.svc.cluster.local
    path: "/"