apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: airflow
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:      
      name: admin-airflow
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: airflow