apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: airflow-webserver-iap
  labels:
    app: airflow
    tier: webserver
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: airflow-webserver-iap
